/**
 * HomeChat — shared types, constants & pure helpers.
 * Extracted from HomeChat.tsx to keep the main component lean.
 */

import { t } from "@/lib/i18n";
import { isPlainObject } from "@/lib/apiError";
import { type ToolSuggestion, type ExecuteResponse } from "@/lib/types";
import { type Nl2UiConfig } from "@/components/nl2ui/DynamicBlockRenderer";

/* ─── Flow types ─────────────────────────────────────────────────────── */

export type AttachmentType = "image" | "document" | "voice" | "video";
export type ChatAttachment = {
  id: string;
  type: AttachmentType;
  name: string;
  size: number;
  previewUrl?: string;
  /** MIME type */
  mimeType: string;
  file?: File;
  duration?: number;
};

export type FlowMessage = { id: string; role: "user" | "assistant"; text: string; attachments?: ChatAttachment[]; createdAt?: number; /** Real-time processing phase from backend (e.g. started/classified/thinking/planning/executing/reviewing) */ phase?: string; /** Model auto-switch notification text (shown when backend falls back to a backup model) */ modelSwitchNote?: string };
export type FlowError = { id: string; role: "assistant"; errorCode: string; message: string; traceId: string; retryMessage?: string; createdAt?: number };
export type UiDirectiveTarget = { kind: "page"; name: string } | { kind: "workbench"; key: string };
export type FlowDirective = { id: string; role: "assistant"; kind: "uiDirective"; directive: unknown; target: UiDirectiveTarget | null; createdAt?: number };
export type FlowNl2UiResult = {
  id: string; role: "assistant"; kind: "nl2uiResult";
  config: Nl2UiConfig;
  userInput: string;
  suggestions: string[];
  createdAt?: number;
};
export type FlowToolSuggestions = { id: string; role: "assistant"; kind: "toolSuggestions"; suggestions: ToolSuggestion[]; turnId?: string; createdAt?: number };

/** Approval node - represents an approval request */
export type FlowApprovalNode = {
  id: string;
  role: "assistant";
  kind: "approvalNode";
  approvalId: string;
  runId: string;
  stepId?: string;
  toolRef: string;
  status: "pending" | "approved" | "rejected";
  requestedAt: string;
  decidedAt?: string;
  createdAt?: number;
  riskLevel?: "low" | "medium" | "high";
  humanSummary?: string;
  inputDigest?: Record<string, unknown>;
};

/** Artifact card — file/data product generated by a tool step */
export type FlowArtifactCard = {
  id: string;
  role: "assistant";
  kind: "artifactCard";
  artifactType: string; // json | table | markdown | text | file
  title: string;
  summary: string | null;
  data: unknown;
  url: string | null; // download url if available
  runId: string | null;
  createdAt?: number;
};

export type ChatFlowItem =
  | ({ kind: "message" } & FlowMessage)
  | ({ kind: "error" } & FlowError)
  | FlowDirective
  | FlowNl2UiResult
  | FlowToolSuggestions
  | FlowApprovalNode
  | FlowTaskQueueEvent
  | FlowArtifactCard;

/** Single step entry for the task progress bar (dual-track output) */
export type TaskStepEntry = {
  id: string;
  seq: number;
  toolRef: string;
  status: "running" | "succeeded" | "failed" | "canceled" | "deadletter";
  reasoning?: string;
  ts: number;
};

/** Aggregated task progress used by TaskProgressBar */
export type TaskProgress = {
  taskId: string;
  runId: string;
  phase: string;
  steps: TaskStepEntry[];
  createdAt: number;
  label?: string; // e.g. "execute" mode label
};

/* ─── Multi-task queue types ────────────────────────────────────────── */

/** 前端版本的队列条目状态 */
export type FrontendQueueStatus =
  | "queued" | "ready" | "executing" | "paused"
  | "completed" | "failed" | "cancelled" | "preempted";

/** 前端版本的任务队列条目 */
export type FrontendTaskQueueEntry = {
  entryId: string;
  taskId: string | null;
  runId: string | null;
  goal: string;
  mode: "answer" | "execute" | "collab";
  priority: number;
  position: number;
  status: FrontendQueueStatus;
  foreground: boolean;
  enqueuedAt: number;
  startedAt: number | null;
  completedAt: number | null;
  retryCount: number;
  lastError: string | null;
  /** 本条目关联的 TaskProgress */
  progress?: TaskProgress;
};

/** 前端版本的任务依赖 */
export type FrontendTaskDependency = {
  depId: string;
  fromEntryId: string;
  toEntryId: string;
  depType: "finish_to_start" | "output_to_input" | "cancel_cascade";
  status: "pending" | "resolved" | "blocked" | "overridden";
};

/** 任务队列整体状态 */
export type TaskQueueState = {
  sessionId: string;
  entries: Map<string, FrontendTaskQueueEntry>;
  dependencies: FrontendTaskDependency[];
  foregroundEntryId: string | null;
  activeCount: number;
  queuedCount: number;
};

/** 多任务进度聚合 */
export type MultiTaskProgress = {
  /** taskId → TaskProgress */
  progressMap: Map<string, TaskProgress>;
  /** 总完成数 */
  completedCount: number;
  /** 总任务数 */
  totalCount: number;
  /** 是否全部完成 */
  allDone: boolean;
};

/** 队列事件流类型（扩展 ChatFlowItem） */
export type FlowTaskQueueEvent = {
  id: string;
  role: "assistant";
  kind: "taskQueueEvent";
  eventType: string;
  entryId?: string;
  taskId?: string | null;
  data: Record<string, unknown>;
  timestamp: number;
  createdAt?: number;
};

export type WorkspaceTab = {
  id: string;
  kind: "page" | "workbench" | "runDetail" | "approvalDetail" | "knowledgeResult" | "artifact" | "nl2uiPreview";
  name: string;
  url: string;
  meta?: {
    runId?: string;
    approvalId?: string;
    artifactType?: "json" | "table" | "chart" | "markdown" | "file" | "text";
    artifactData?: unknown;
    nl2uiConfig?: unknown; // For nl2uiPreview kind
  };
};

export type ToolExecState =
  | { status: "idle" }
  | { status: "executing" }
  | { status: "polling"; runId: string; runStatus?: string }
  | { status: "done"; result: ExecuteResponse; runStatus?: string; stepOutput?: unknown; stepError?: string }
  | { status: "error"; message: string };

/* ─── Constants ──────────────────────────────────────────────────────── */

/** Terminal run statuses – stop polling when we see one of these */
export const TERMINAL_RUN_STATUSES = new Set(["succeeded", "failed", "canceled", "deadletter"]);

/** Terminal queue statuses */
export const TERMINAL_QUEUE_STATUSES = new Set<FrontendQueueStatus>(["completed", "failed", "cancelled"]);

export const NAV_ITEMS = [
  { key: "runs", href: "/runs" },
  { key: "tasks", href: "/tasks" },
  { key: "orchestrator", href: "/orchestrator" },
  { key: "governance", href: "/gov/changesets" },
  { key: "settings", href: "/settings" },
] as const;

/* ─── Recent pages (localStorage) ────────────────────────────────────── */

export type RecentEntry = { kind: "page" | "workbench"; name: string; ts: number; url?: string };
const RECENT_KEY = "openslin_recent_pages";
const MAX_RECENT = 12;

export function loadRecent(): RecentEntry[] {
  if (typeof window === "undefined") return [];
  try { const raw = localStorage.getItem(RECENT_KEY); return raw ? (JSON.parse(raw) as RecentEntry[]) : []; }
  catch { return []; /* expected: localStorage/JSON.parse may throw in restricted env */ }
}

export function addRecent(entry: Omit<RecentEntry, "ts">) {
  const list = loadRecent().filter((r) => !(r.kind === entry.kind && r.name === entry.name));
  list.unshift({ ...entry, ts: Date.now() });
  if (list.length > MAX_RECENT) list.length = MAX_RECENT;
    try { localStorage.setItem(RECENT_KEY, JSON.stringify(list)); } catch { /* expected: localStorage may be restricted */ }
  return list;
}

export function clearRecent() {
    try { localStorage.removeItem(RECENT_KEY); } catch { /* expected: localStorage may be restricted */ }
}

/* ─── Favorites (localStorage) ───────────────────────────────────────── */

export type FavoriteEntry = { kind: "page" | "workbench" | "run" | "agent"; name: string; url: string; addedAt: number };
const FAVORITES_KEY = "openslin_favorites";
const MAX_FAVORITES = 20;

export function loadFavorites(): FavoriteEntry[] {
  try { const raw = localStorage.getItem(FAVORITES_KEY); return raw ? (JSON.parse(raw) as FavoriteEntry[]) : []; }
  catch { return []; /* expected: localStorage/JSON.parse may throw in restricted env */ }
}

export function addFavorite(entry: Omit<FavoriteEntry, "addedAt">): FavoriteEntry[] {
  const list = loadFavorites().filter((f) => !(f.kind === entry.kind && f.name === entry.name));
  list.unshift({ ...entry, addedAt: Date.now() });
  if (list.length > MAX_FAVORITES) list.length = MAX_FAVORITES;
  try { localStorage.setItem(FAVORITES_KEY, JSON.stringify(list)); } catch { /* expected: localStorage may be restricted */ }
  return list;
}

export function removeFavorite(kind: string, name: string): FavoriteEntry[] {
  const list = loadFavorites().filter((f) => !(f.kind === kind && f.name === name));
  try { localStorage.setItem(FAVORITES_KEY, JSON.stringify(list)); } catch { /* expected: localStorage may be restricted */ }
  return list;
}

export function isFavorite(kind: string, name: string): boolean {
  return loadFavorites().some((f) => f.kind === kind && f.name === name);
}

export function clearFavorites() {
    try { localStorage.removeItem(FAVORITES_KEY); } catch { /* expected: localStorage may be restricted */ }
}

/* ─── Tool helpers ───────────────────────────────────────────────────── */

export function parseToolRef(toolRef: string) {
  const idx = toolRef.lastIndexOf("@");
  const name = idx > 0 ? toolRef.slice(0, idx) : toolRef;
  const version = idx > 0 ? toolRef.slice(idx + 1) : "";
  return { name, version };
}

export function friendlyToolName(locale: string, toolRef: string): string {
  const { name } = parseToolRef(toolRef);
  const key = `chat.toolSuggestion.toolName.${name}`;
  const label = t(locale, key);
  return label !== key ? label : name;
}

export function riskBadgeKey(risk: string): string {
  const r = risk.toLowerCase();
  if (r === "low") return "chat.toolSuggestion.risk.low";
  if (r === "medium" || r === "med") return "chat.toolSuggestion.risk.medium";
  if (r === "high") return "chat.toolSuggestion.risk.high";
  return "chat.toolSuggestion.risk.low";
}

export function friendlyOutputSummary(locale: string, toolRef: string, outputDigest: unknown): { text: string; latencyMs?: number } {
  const toolName = friendlyToolName(locale, toolRef);
  const text = t(locale, "chat.toolSuggestion.outputSummary").replace("{tool}", toolName);
  const latencyMs = isPlainObject(outputDigest) && typeof (outputDigest as Record<string, unknown>).latencyMs === "number" ? (outputDigest as Record<string, unknown>).latencyMs as number : undefined;
  return { text, latencyMs };
}

/** Convert technical error codes into user-friendly messages. */
export function friendlyErrorMessage(locale: string, errorCode: string, message?: string): string {
  const code = String(errorCode ?? "").trim();
  if (code) {
    const key = `chat.error.${code}`;
    const mapped = t(locale, key);
    if (mapped !== key) return mapped;
  }
  if (message) return message;
  return t(locale, "chat.error.unknown");
}

export function targetFromUiDirective(d: unknown): UiDirectiveTarget | null {
  if (!isPlainObject(d)) return null;
  const viewParams = d.viewParams;
  if (!isPlainObject(viewParams)) return null;
  if (d.openView === "page") { const n = viewParams.name; if (typeof n !== "string" || !n.trim()) return null; return { kind: "page", name: n.trim() }; }
  if (d.openView === "workbench") { const k = (viewParams.key ?? viewParams.workbenchKey); const key = typeof k === "string" ? k.trim() : ""; if (!key) return null; return { kind: "workbench", key }; }
  return null;
}

/**
 * riskBadgeClass needs CSS module reference — pass the styles object.
 * Returns the appropriate badge CSS class for the given risk level.
 */
export function riskBadgeClass(risk: string, cssStyles: Record<string, string>): string {
  const r = risk.toLowerCase();
  if (r === "medium" || r === "med") return cssStyles.toolSuggestionBadgeMedium;
  if (r === "high") return cssStyles.toolSuggestionBadgeHigh;
  return cssStyles.toolSuggestionBadgeLow;
}
