/**
 * Skill RPC Protocol (S02)
 * Re-exported from @mindpal/protocol - the single source of truth.
 */
export {
  SKILL_RPC_VERSION,
  SKILL_RPC_JSONRPC,
  DEVICE_PROTOCOL_VERSION,
  MIN_SUPPORTED_PROTOCOL_VERSION,
  PROTOCOL_VERSIONS,
  SKILL_RPC_ERRORS,
  SKILL_RPC_METHODS,
  isVersionCompatible,
  negotiateVersion,
  createRpcRequest,
  createRpcSuccess,
  createRpcError,
  createRpcNotification,
  serializeRpcMessage,
  parseRpcMessage,
  isRpcRequest,
  isRpcNotification,
  isRpcResponse,
  isRpcError,
} from '@mindpal/protocol';

export type {
  ProtocolVersion,
  ProtocolHandshake,
  ProtocolHandshakeAck,
  DeviceModality,
  DeviceMultimodalCapabilities,
  DeviceMultimodalPolicy,
  DeviceAttachment,
  DeviceMultimodalQuery,
  DeviceMultimodalResponse,
  SkillRpcRequest,
  SkillRpcSuccess,
  SkillRpcError,
  SkillRpcNotification,
  SkillRpcResponse,
  SkillRpcMessage,
  SkillInitializeParams,
  SkillInitializeResult,
  SkillExecuteParams,
  SkillExecuteResult,
  SkillHeartbeatParams,
  SkillHeartbeatResult,
  SkillProgressNotification,
  SkillLogNotification,
} from '@mindpal/protocol';
